### ISSUE TITLE
Empire agent breaking backend by sending multiple cookies with unique ID

### ISSUE THREAD

**Issue by 0x3a** [adaptivethreat/Empire#239]
## OS Information (Linux flavor, Python version)

Running Empire on the latest Kali (Linux kali 4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-7kali2 (2016-01-27) x86_64 GNU/Linux)
Python 2.7.11
Target OS - Microsoft Windows 10 Version 10.0.10586
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

I've been working on a setup where I log into a remote VPS using reverse tunneling with SSH (ssh -R 8080:localhost:8080 <remote host>) and the VPS has NGINX to upstream requests to localhost:8080. This forwarding requests works fine, I can test this with my browser as well as a stager connecting for the first time. _Update_: I have now also tested this with a plain TCP proxy, this seems to a bug in the agent.

As soon as a launcher has downloaded the stager it decrypts it properly but when this connects the first time it works, second time empire actually breaks:

> ---
> 
> Exception happened during processing of request from ('127.0.0.1', 36940)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
>     self.finish_request(request, client_address)
>   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
>     self.handle()
>   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
>     self.handle_one_request()
>   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
>     method()
>   File "/root/Documents/Empire/lib/common/http.py", line 80, in do_GET
>     name, sessionID = part.split("=")
> ## ValueError: too many values to unpack

Looking at a capture I can see what is happening:

> GET /index.asp HTTP/1.1
> Cookie: SESSIONID=F2CC4EMAC2W1KSYF,SESSIONID=GT3PMXT1WPUNMYNF

Somehow the client checks in with two IDs. I originally thought this was caused by NGINX itself (I'm still unsure) so I disabled any _Set-Cookie_ headers but the agent should send this header itself, it isn't set through any Set-Cookie from the empire backend. Current configuration for NGINX is:

> server {
>        listen 80;
> 
> ```
>    location / {
>            proxy_pass https://localhost:8080;
>    }
> ```
> 
> }
## Screenshot of error, embedded text output, or Pastebin link to the error

Mentioned above in the description.

**Comment by 0x3a** [comment]
I get why it breaks from looking at the code, I don't get why the agent would send these multiple IDs from a clean system.

**Comment by 0x3a** [comment]
Was digging some more, found the issue comes when you set a launcher to use >1 attempts. It adds a new ID to the list of ID's for the checkin. This is what happens when I set the launcher to use 10 attempts:

> GET /index.asp HTTP/1.1
> Cookie: SESSIONID=XLZNMHS4WKSD2UTD,SESSIONID=CFVDMEALMLBPWVCS,SESSIONID=XCKEHYUR4HVTAWTG,SESSIONID=1NVFNDUN1ZFL4YMF,SESSIONID=P34XKW1RUXBCNLWK,SESSIONID=RMG4YKHP1XA1XMAU,SESSIONID=SW4212LXSVEGZCNN,SESSIONID=YZGM4ZP3XGZFAWMM,SESSIONID=VAZAAUFBAEHMZXMB
> Host: AAAAABLABLABLA
> Connection: Keep-Alive
> 
> HTTP/1.0 200 OK
> Server: Microsoft-IIS/7.5 
> Date: Sun, 05 Jun 2016 21:33:37 GMT

**Comment by GILoe** [comment]
I was having the same issue with the cookies field that contain multiple unique ID's, but in the do_POST() method at line 95 (defined right below the do_GET() ).
Could be a different issue, but it occurred when I was attempting to go through proxies as well.
In my case, the culprit was hiding at line 104, with the delimiter ';' of the cookie.split method.
Changing the delimiter to ',', as in
`parts = cookie.split(",")`
each part (in parts) was having a clean sessionID to be extracted and everything going smoothly afterwards.

Maybe because this problem comes up only when using intermediates, it has not been issued separately (and I am hesitant to do so myself as too new in here). But after my 'fix' it still function, intermediates (hops) or not.
Hope this helps !

**Comment by enigma0x3** [comment]
@0x3a,
Do you mind giving the above solution a try and see what happens?

Thanks!

**Comment by 0x3a** [comment]
That fix worked, sorry I never replied to this issue. Not sure if its a nice fix as the IDs that are cached might be different in order? (not sure how cookie order is specified).

**Comment by qgrosperrin** [comment]
I have an issue similar to that. I'm using Empire 1.6.

When creating a launcher for an HTTPS listener with anything different than StagerRetries set to 0, the launcher will not work properly (though I can see some hits in the access logs). If I use StagerRetries > 1, I get an error message similar to the following: 

```
----------------------------------------
Exception happened during processing of request from ('X.X.X.X', 56853)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 122, in do_POST
    name, sessionID = part.split("=")
ValueError: too many values to unpack
----------------------------------------
```

Note: this message is printed once when using StagerRetries = 2, twice when using StagerRetries = 3, etc..

**Comment by xorrior** [comment]
@qgrosperrin Can you test this with the 2.0_beta branch??

**Comment by xorrior** [comment]
@qgrosperrin I'm am going to close this out. If you can replicate this, just comment here and we can revisit this.
