### ISSUE TITLE
Incoming malformed requests cause listener crash

### ISSUE THREAD

**Issue by curi0usJack** [adaptivethreat/Empire#293]
## Empire Version
1.5

## OS Information (Linux flavor, Python version)
ubuntu 14.04, python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Every so often an incoming request (non-agent) appears to crash the listener. This results in all the agents going stale if not caught & fixed quickly enough. I am not positive that this is the case of agents going stale, only that the behavior seems to be consistent and has happened on a number of engagements. When this happens, empire hangs when shutting down, as does attempting to kill the listener. There are three potential fixes:

1) Kill listener PID, relaunch empire. Works 75% of the time or so.
2) If #1 doesn't work, kill empire, then use sqlite3 to remove listener entry from the db.
3) If that doesn't work, clone & start over.

Example Exception:
![image](https://cloud.githubusercontent.com/assets/5608516/17388990/ca4fb7c2-59c5-11e6-80b0-6caebe606fcd.png)

Generally, I see this kind of crap from China, but not always and I am hesitant to just start firewalling off as I'm not sure where my incoming agents will originate from.

**Comment by enigma0x3** [comment]
Thanks for reporting this. It looks like this is a result of people "scanning" or fuzzing python's baseHTTPServer (likely mass scans):  https://corte.si/posts/code/pathod/pythonservers/index.html#simplehttp

 In the meantime, you can probably firewall off any repeat offenders
We will look into a fix for this.

**Comment by HarmJ0y** [comment]
The HTTP listeners in the 2.0 rewrite (out in a few weeks at DerbyCon) migrates to Flask instead of the existing HTTP handler code, so this should hopefully be resolved in a few weeks.

**Comment by curi0usJack** [comment]
Win. Thanks!

**Comment by enigma0x3** [comment]
@curi0usJack, this should be fixed in 2.0 by switching to Flask for HTTP handling.

Thanks!

**Comment by curi0usJack** [comment]
Awesome. Thanks Matt!
