### ISSUE TITLE
Token Manipulation as System Issues

### ISSUE THREAD

**Issue by NnB01** [adaptivethreat/Empire#302]
## Empire Version

Version 1.5.0
## OS Information (Linux flavor, Python version)

Kali Linux 2016.1 64-bit Rolling
Python 2.7.12+
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Scenario:  infected machine: WIN7 Pro N x64 system , attacker machine: Kali Linux 2016.1 x64 Rolling
Run empire payload on the infected machine  , elevate to administrator -> elevate to System , create a service that starts an empire .bat payload with system privileges every time the infected machine boots. This scenario works perfectly, infected machine boots and a connection is established with the attackers machine.
Error: While interacting with the system privileged agent (after infected machine boots) i noticed that module credentials/tokens doesn't work at all either by trying to impersonate the users token (known issue) or by trying to spawn a new process with users tokens.
## Screenshot of error, embedded text output, or Pastebin link to the error

![high_int_agent](https://cloud.githubusercontent.com/assets/21063734/17710370/98dc5288-63f5-11e6-8360-c13cd05eb7f5.png)

Empire .bat payload is located in C:\Windows\SysWOW64 and is named test.bat

![error_no_spawn](https://cloud.githubusercontent.com/assets/21063734/17710470/0bca0c5e-63f6-11e6-9653-21d894f1cad5.png)

Then nothing happens , no new Process with Users token is ever created.
## Any additional information

1)If .bat payload is executed from user of the infected machine then i can elevate all the way to System and execute same way as described above. This way everything works as expected.
2)Above described steps work perfectly on WIN10 Home Edition x64 OS but not on WIN7 Pro N x64 OS

**Comment by HarmJ0y** [comment]
From the agent menu, can you try "steal_token <PID>" and then "spawn <listener>" to see if that works?

**Comment by NnB01** [comment]
Output of what you asked (stole explorer.exe PID (1264))

![spawn](https://cloud.githubusercontent.com/assets/21063734/18178509/4ece87a8-7087-11e6-8b7a-92a1240f5c09.png)

It works fine but if i try again what i did above, using the new spawned agent this time, still command does not get executed

![fail](https://cloud.githubusercontent.com/assets/21063734/18178666/ee8f6a82-7087-11e6-8220-0be3f0a418d1.png)

Also i noticed a really strange bug. Once victim-pc boots and the connection to my attackers box gets established, if i execute credentials/tokens several times i get different results. As you can see in the screenshot below, i executed credentials/tokens module 3 times.

![bug](https://cloud.githubusercontent.com/assets/21063734/18179083/90c2b114-7089-11e6-8d8c-0aee29c0ebe0.png)

Then again if i keep executing the module ProcessID disappears, IsElevated shows false and TokenType changes to Impersonation.

**Comment by enigma0x3** [comment]
What happens if you try to use Invoke-TokenManipulation by itself instead of within Empire?

**Comment by xorrior** [comment]
No response. Please re-open or create another git issue if you continue to have problems. There hasn't been any issues explaining this type of behavior with Invoke-TokenManipulation.
