### ISSUE TITLE
WMI Lateral Movement

### ISSUE THREAD

**Issue by jc1396** [adaptivethreat/Empire#313]
I am using an external C2 server with a signed SSL Cert.  I am able to compromise a workstation in the environment.  I am able to escalate privileges on the host as well.  When I try to use invoke_wmi to move to a different workstation, it executes, but the new workstation never calls back to C2 server with new agent.  

When I conduct the same procedures locally not using signed SSL Cert, I am able to move laterally using WMI on the same workstation.

I have tried setting up a pivot listener on the first workstation and redirect to the original listener, but I get the same results.

Can some please let me know if I have missed a step or if this is possible using a signed SSL Cert?

**Comment by enigma0x3** [comment]
What do you mean by "locally"? Inside the target environment or in your personal lab?

**Comment by jc1396** [comment]
Yes, when I say "locally", I am on our internal LAN subnet.  I have no issues testing this way.  The issue arises when I try to move latterly from the first compromised target from the external C2 server.  The first compromised target communicates to my external C2 server fine, but when I try to latterly move to the second target, I do not get a new agent from the second target to my C2 server.  My thought is that our corporate proxy server is blocking the communication?

**Comment by HarmJ0y** [comment]
Seems like it's likely a proxy issue? In the next few weeks we're going to implement manual proxy specification into the 2.0_beta branch (https://github.com/adaptivethreat/Empire/tree/2.0_beta), which might solve your problem.

**Comment by xorrior** [comment]
This looks like an environment specific issue.
