### ISSUE TITLE
Screenshot module throws an error if used on system shells

### ISSUE THREAD

**Issue by Viss** [adaptivethreat/Empire#319]
## Empire Version
current out of dev 

If the shell is owned by the user, or even an elevated user shell, the screenshot module works fine, if the shell is a system shell, a sort of broken error is displayed:

> Output saved to ./downloads/YCLK1ETLVDBK1AEL/error running c/MNET-M1_2016-09-17_21-25-19.omman

I'm not sure if this is because the backend screenshot tool needs to be in a users context, or because something is actually broken. I'm not sure how to troubleshoot this myself.

**Comment by leesoh** [comment]
@Viss @enigma0x3 This is the same error I get when the screenshot module is being screwy. Does your keylogging also not work?

**Comment by Viss** [comment]
@leesoh I only get that error when attempting to take screenshots from a system shell. Keylogs are still missing keystrokes, reporting things out of order, and displaying results in a mostly-unusable fashion, so I'm still using msf for keystroke collection. Using empire for screenshot collection as it appears to be far more stable, and I'm working on a thing I'm tentatively calling 'jarvis' that's a wrapper for the api which will find unique agents on machines that have a bunch of agents, and only target a single agent per machine to launch screenshots, then move the screenshots to another directory for viewing. 

course.. this breaks, since at the moment I haven't written a routine that will omit system shells, so if the first shell on the box it finds to target happens to be a system shell, it just throws errors, versus actually capturing screenshots ;b

**Comment by leesoh** [comment]
@Viss Yeah, the reason I asked is that both screenshots and keylogging seem to work or not work at the same time. If your keylogger is broken (no output) at the same time as your screenshot error popping up, we may have the same problem with you providing a bit more useful information than I've been able to.

**Comment by Viss** [comment]
ah - yeah, I think it's got something to do with the context. If its a system shell then it's not in the context of the user - thats about all I've been able to come up with.

**Comment by leesoh** [comment]
False alarm. Tested this morning on a Windows 7 box. Under regular user, administrator, and system I'm able to get both screenshots and keystrokes (same inaccuracies you mention). I had two agent sessions, one for regular user, then one as administrator/system. Error is definitely the same though (Issue #187)

**Comment by Viss** [comment]
er, are you indicating that with a system shell you have the same problems as I'm describing?

**Comment by leesoh** [comment]
No, sorry. The error you were getting was identical to the error I was getting with my screenshots (#187). Been having a hell of a time tracking down the cause, so I thought your and my issues may be related. However, I'm able to screenshot/keylog with no issues in user/admin/system shells, so I think you've found a brand new headache :)

**Comment by Viss** [comment]
I should mention that these problems I'm having are in windows 10 workstations, not any server OS, and so far it's happened on every windows 10 box I've touched. If you have a system shell you can do neat things like mimikatz, but you can't screenshot. I can test keylogging to be sure

**Comment by mynameisv** [comment]
Hi, the issue is normal, it's not a bug in Empire.
When you're SYSTEM, you're trying to take a screenshot of the your device context / display (not the user one) that do not exists.
You've to spawn a shell in user's space and do a screenshot.

**Comment by rvrsh3ll** [comment]
mynameisv is correct. you need to be in the context of the user you want to screenshot.
