### ISSUE TITLE
Install Empire Error

### ISSUE THREAD

**Issue by phnorngsenghorng** [adaptivethreat/Empire#321]
+ I installing show error as this,

root@sohee:~/Desktop/Tools/Empire/setup# ./install.sh 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-dev is already the newest version (2.7.11-2).
The following packages were automatically installed and are no longer required:
  gir1.2-evince-3.0 hwdata libfftw3-single3 libnm-glib-vpn1
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 27 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-m2crypto is already the newest version (0.24.0-1).
The following packages were automatically installed and are no longer required:
  gir1.2-evince-3.0 hwdata libfftw3-single3 libnm-glib-vpn1
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 27 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
swig is already the newest version (3.0.7-2.1).
The following packages were automatically installed and are no longer required:
  gir1.2-evince-3.0 hwdata libfftw3-single3 libnm-glib-vpn1
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 27 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version (8.1.2-2).
The following packages were automatically installed and are no longer required:
  gir1.2-evince-3.0 hwdata libfftw3-single3 libnm-glib-vpn1
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 27 not upgraded.
Requirement already satisfied (use --upgrade to upgrade): pycrypto in /usr/lib/python2.7/dist-packages
Collecting iptools
  

> Could not find a version that satisfies the requirement iptools (from versions: )
> No matching distribution found for iptools

Collecting pydispatcher
 

>  Could not find a version that satisfies the requirement pydispatcher (from versions: )
> No matching distribution found for pydispatcher

Requirement already satisfied (use --upgrade to upgrade): flask in /usr/lib/python2.7/dist-packages

 [>] Enter server negotiation password, enter for random generation: abc123
Traceback (most recent call last):
  File "./setup_database.py", line 118, in <module>
    )''')
sqlite3.OperationalError: table config already exists

 [*] Certificate written to ../data/empire.pem

 [*] Setup complete!

+ Run empire show error as bellow: 

Traceback (most recent call last):
  File "./empire", line 10, in <module>
    from lib.common import empire
  File "/root/Desktop/Tools/Empire/lib/common/empire.py", line 21, in <module>
    import helpers
  File "/root/Desktop/Tools/Empire/lib/common/helpers.py", line 10, in <module>
    import re, string, commands, base64, binascii, sys, os, socket, sqlite3, iptools
ImportError: No module named iptools

Please help me, thanks you so much.

**Comment by HarmJ0y** [comment]
Can you please resubmit using the GitHub issue template so we know what OS/Empire/etc. version you are using.
