### ISSUE TITLE
run issue on kali rolling nexus

### ISSUE THREAD

**Issue by dan7ez** [adaptivethreat/Empire#322]
## Empire Version
1.6

## OS Information (Linux flavor, Python version)

kali rolling 2016 on nexus 9 tablet
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Empire 1.5 works perfect but when i try and run 1.6 i get this error

## Screenshot of error, embedded text output, or Pastebin link to the error
root@localhost:/opt# cd Empire-master16/
root@localhost:/opt/Empire-master16# ./empire
Traceback (most recent call last):
  File "./empire", line 1237, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/Empire-master16/lib/common/empire.py", line 81, in __init__
    self.stagers = stagers.Stagers(self, args=args)
  File "/opt/Empire-master16/lib/common/stagers.py", line 47, in __init__
    self.load_stagers()
  File "/opt/Empire-master16/lib/common/stagers.py", line 66, in load_stagers
    self.stagers[stagerName] = imp.load_source(stagerName, filePath).Stager(self.mainMenu, [])
AttributeError: 'module' object has no attribute 'Stager'
root@localhost:/opt/Empire-master16#

**Comment by HarmJ0y** [comment]
Did you run the ./setup/install.sh script to install the project? If you already have, can you try running ./setup/reset.sh and see if the issue is still there?

**Comment by dan7ez** [comment]
Hi Harmjoy,

thanks for your quick reply!

I tried that, however, unfortunately the same error prevails :(

please advise?

Many Thanks,
dan7ez

**Comment by dan7ez** [comment]
Hi Harmjoy,

disregard all my previous messages... this issue is fixed

 I deleted the file I had there and simply git cloned and installed... and it all works perfect!

guess i should have done that first time...

Thanks for all your help and all the best with your fine work in the future!

Kind Regards,
Dan7ez
