### ISSUE TITLE
set Autorun script per Listener?

### ISSUE THREAD

**Issue by thesle3p** [adaptivethreat/Empire#328]
Hi, I am probably being stupid but is there not a way to set a Autorun script per listener? Like to be run when ever that listener receives a checkin or spawns a new agent from a stager? I vaguely remember seeing a commit for that but can't seem to find any reference to it in the UI.

**Comment by bneg** [comment]
Yes. Is possible. https://github.com/PowerShellEmpire/Empire/issues/80#issuecomment-158811283

**Comment by thesle3p** [comment]
Thanks.
