### ISSUE TITLE
/api/admin/login not working with --username and/or --password options

### ISSUE THREAD

**Issue by tristandostaler** [adaptivethreat/Empire#331]
## Empire Version
Most recent

## OS Information (Linux flavor, Python version)
Ubuntu

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When you start the server with "./empire --username test --password test --headless" you could then get the token with:
"curl --insecure -i -H "Content-Type: application/json" https://127.0.0.1:1337/api/admin/login -X POST -d '{"username":"test", "password":"test"}'". Right now, it does not work.
The error comes from the fact that in the flask part, in the part:
@app.route('/api/admin/login', methods=['POST'])
    def server_login():
the "username" variable is an array and "return ' '.join(username)" and doing the curl request returns:
HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 7
Server: Werkzeug/0.11.9
Date: Fri, 23 Sep 2016 22:25:27 GMT

t e s t%    

Solution:

The simplest solution is to do the following (the modification in **bold**):
 if suppliedUsername == **''.join(username)** and suppliedPassword == **''.join(password)**:

@app.route('/api/admin/login', methods=['POST'])
    def server_login():
        """
        Takes a supplied username and password and returns the current API token
        if authentication is accepted.
        """

        if not request.json or not 'username' in request.json or not 'password' in request.json:
            abort(400)

        suppliedUsername = request.json['username']
        suppliedPassword = request.json['password']

        # try to prevent some basic bruting
        time.sleep(2)

        if suppliedUsername == ''.join(username) and suppliedPassword == ''.join(password):
            return jsonify({'token': apiToken})
        else:
            return make_response('', 401)

**Comment by leesoh** [comment]
This is a duplicate of #329 AND #330 ;)

**Comment by tristandostaler** [comment]
Lol I even looked for duplicate before posting!
Thanks!
