### ISSUE TITLE
HTTP listeners erroring out in v2.0 beta

### ISSUE THREAD

**Issue by atkinsj** [adaptivethreat/Empire#333]
## Empire Version
2.0 beta -- I know you guys just hit this 16 hours ago but I'm keen! Let me know if you don't want anymore 2.0 bug reports.

## OS Information (Linux flavor, Python version)
Kali rolling, aptitude upgraded prior to running

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

- uselistener http
- execute
- launcher powershell http
- paste powershell launcher output on to a host (I tested a fully updated Server 2008 R2 host, a Server 2012 host and a Windows 8.1 host)
- error produced

## Screenshot of error, embedded text output, or Pastebin link to the error

> (Empire: listeners) > [2016-09-17 22:37:39,841] ERROR in app: Exception on /login/process.php [GET]
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/root/empire//lib/listeners/http.py", line 697, in handle_get
>     stage = self.generate_stager(language=language, listenerOptions=listenerOptions)
>   File "/root/empire//lib/listeners/http.py", line 328, in generate_stager
>     f = open("%s/data/agent/stagers/http.ps1" % (self.mainMenu.installPath))
> IOError: [Errno 2] No such file or directory: u'/root/empire//data/agent/stagers/http.ps1'

**Comment by enigma0x3** [comment]
Thanks for checking the code out! We appreciate the bug reports, so keep them coming!

Is this a fresh clone or a git pull from the old project? For starters, I would just remove the project and re-clone it. Then do "git checkout 2.0_beta", run the install script and then run "reset.sh". Once up, can you validate that "data/agent/stagers/http.ps1" exists?

**Comment by atkinsj** [comment]
Yup -- that's it, totally my snafu. It was a pull/checkout but a fresh clone sorted it.

Thanks!

**Comment by HarmJ0y** [comment]
Great! We should probably be more clear with the instructions, we'll updated the README/wiki in the next few weeks.
