### ISSUE TITLE
Unknown syntax (Options in Listeners)

### ISSUE THREAD

**Issue by skuta** [adaptivethreat/Empire#334]
## Empire Version
2.0_beta

## OS Information (Linux flavor, Python version)
Kali 2.0,  Python 2.7.12+

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Want to see the options of listeners and actually create some.

## Screenshot of error, embedded text output, or Pastebin link to the error
(Empire) > listeners
[!] No listeners currently active 
(Empire: listeners) > options
*** Unknown syntax: options

**Comment by leesoh** [comment]
Looks like things changed a bit.
1. uselistener [TAB]
2. Pick a listener
3. Set options
4. Execute

**Comment by skuta** [comment]
Thanks! I was looking for usestager launcher and it does not exist?

**Comment by bovas85** [comment]
How do you actually create one in 2.0 though?

**Comment by anonhazard** [comment]
I am having problems with the commands mentioned above.
![edit](https://cloud.githubusercontent.com/assets/29004265/26524967/d8bc8d70-431d-11e7-9cdc-88eef85e4d75.jpg)

**Comment by xorrior** [comment]
https://www.harmj0y.net/blog/empire/the-empire-strikes-back/. <<<< Updated syntax is documented in this post.

**Comment by mateo24xx** [comment]
thank you friend this shit make me crazy .
.but am must say big big up for the guy's from "The Empire Strikes Back" they did a very good job updating and put new stuff in it
