### ISSUE TITLE
Empire Linux agent fails with syntax error

### ISSUE THREAD

**Issue by atkinsj** [adaptivethreat/Empire#335]
## Empire Version
2.0 beta

## OS Information (Linux flavor, Python version)
Empire C2 - Kali 
Tested Python version - Python 2.7.9

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Using a http listener to a https address and a standard Python stager. Execution of the stager succeeds and an agent is deployed, successfully appearing in the Empire C2. No further beacons are received and the following error message is displayed on the agent host:

```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "<string>", line 19, in <module>
>   File "<string>", line 577, in <module>
>   File "<string>", line 45
>     import ssl;if hasattr(ssl, '_create_unverified_context'):ssl._create_default_https_context = ssl._create_unverified_context;
>                 ^
> SyntaxError: invalid syntax
> 
```

**Comment by vector-sec** [comment]
Seeing this as well on OSX and Ubuntu as the agent host.

**Comment by rvrsh3ll** [comment]
Thanks for the issue notification. I'll be checking out and will get back to you soon.

**Comment by rvrsh3ll** [comment]
atkinsj - what was the OS the agent was running on ? was it a VPS?

**Comment by rvrsh3ll** [comment]
This issue has been fixed. You can now also auto generate an inline certificate just by setting the host to Host https://ip/
Thank you for your submission! Please let is know if you have any further issues.
