### ISSUE TITLE
Listener's stager/multi/launcher is not giving me a one-liner

### ISSUE THREAD

**Issue by DIRTYPIRATE** [adaptivethreat/Empire#337]
## Empire Version
Beta_2.0

## OS Information (Linux flavor, Python version)
Parrot Security OS 3.1

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Expected behavior: Having a listener setup and execute the one liner launcher to receive powershell code.

The error: The output after I type "generate" in "Empire: stager/multi/launcher" doesn't give me the one-liner, but a load of code that I frankly do not understand and is unusable.
## Screenshot of error, embedded text output, or Pastebin link to the error
http://pastebin.com/VX0Q4Krn

## Any additional information
Fresh install of Empire beta_2.0
I uninstalled empire 1.6 before, so that may have an issue with it, but i doubt it.

**Comment by skuta** [comment]
What listener did you use? 

It works for me with http listener.

**Comment by rvrsh3ll** [comment]
I'll be testing on that OS today. Thank you for the issue notification.

**Comment by rvrsh3ll** [comment]
I have tested this in a fresh Parrot OS install and it works fine. Make sure you set the listener first with "set Listener http".
