### ISSUE TITLE
New install.sh does not grab all necessary dependencies 

### ISSUE THREAD

**Issue by atkinsj** [adaptivethreat/Empire#340]
## Empire Version
2.0_beta

## OS Information (Linux flavor, Python version)
Kali rolling

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Running ./setup/install.sh does not grab the new dependencies required to compile 'xar'. This is evident on at least Kali rolling and probably other platforms as well.

## Screenshot of error, embedded text output, or Pastebin link to the error

> [ ... snip ... ]
> configure: error: Cannot build without libcrypto (OpenSSL)
> make: *** No targets specified and no makefile found.  Stop.
> make: *** No rule to make target 'install'.  Stop.
> Cloning into 'bomutils'...

I believe the Debian/Ubuntu/Kali/etc package that needs to be included is 'libssl-dev'.

**Comment by rvrsh3ll** [comment]
Thank you for the issue report. We're on it.

**Comment by Brockway** [comment]
hi, kali rolling 2016.2, latest version of empire install script shows that i have the latest version of libssl-dev (1.1.0f-3) but still has the exact same error -

configure: error: Cannot build without libcrypto (OpenSSL)
make: *** No targets specified and no makefile found. Stop.
make: *** No rule to make target 'install'. Stop.
Cloning into 'bomutils'...

Empire finishes compiling but will be missing xar functionality
