### ISSUE TITLE
empire 1.0 and 2.0 shells incompatible

### ISSUE THREAD

**Issue by Viss** [adaptivethreat/Empire#347]
Empire 1.0 shells phoning home into a 2.0 environment do not stage up.

Phobos does these really long haul engagements. At the moment we have several dozen machines across several orgs all phoning home every day at multiple times. 

As it stands, it would be very difficult to hot-swap empire1.0 out for 2.0 mid stream. 

I'd like to request a 1.0 stager module be put into empire 2.0, to help facilitate the migration of the old environment out to the new environment.

**Comment by leesoh** [comment]
Hey Viss - don't know if you saw this yet or not: http://www.harmj0y.net/blog/empire/the-empire-strikes-back/
> We also still need to work out a proper methodology for migrating agents from 1.X to 2.X, which we’re hoping to work out in the next few weeks.

**Comment by Viss** [comment]
That was posted today :)

**Comment by leesoh** [comment]
Yeah! Didn't know if you'd seen it so I figured I'd just drop it in here :)

**Comment by Viss** [comment]
ohyes.
phobos is actively developing modules, and we had one we were gonna commit but the module format changed between 1 and 2, so we hafta tweak it a bit.

expect to see a pr from us this week :D

**Comment by rvrsh3ll** [comment]
Sounds good Viss thanks! Typically, we'd have you migrate your persistence/agents to the new format. If you're willing to roll dev on prod :P

**Comment by Viss** [comment]
Im already running the dev branch :D

**Comment by Viss** [comment]
if you got pointers, im all ears, but i wager just temporarily adding a 1.0 listener into 2.0 as one of the options would do the trick - i could use the thing I wrote that talks to the api to migrate every agent to the new format.

**Comment by rvrsh3ll** [comment]
if you have a solution, we're all ears 👍

**Comment by rvrsh3ll** [comment]
and feel free to join us on http://adaptiveempire.herokuapp.com/

**Comment by HarmJ0y** [comment]
After discussion we decided that we are not going to officially support 1.X -> 2.X compatibility. You should be able to generate a new 2.0 launcher and spawn that from 1.0 agent. We will update the wiki in the next few weeks to detail this process.
