### ISSUE TITLE
2.0 failed .bat launcher

### ISSUE THREAD

**Issue by choppersec** [adaptivethreat/Empire#349]
## Empire Version
BETA 2.0

## OS Information (Linux flavor, Python version)
Kali, Python 2.7, Windows 10 Enterprise VM

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
I tried to generate a launcher.bat but when I execute it on the target host I get an error reading:
"Windows cannot find 'function'. Make sure you typed the name correctly, and then try again."

## Screenshot of error, embedded text output, or Pastebin link to the error
![bat_error](https://cloud.githubusercontent.com/assets/22639984/19122037/b079b62c-8b20-11e6-9aba-19afec741e76.png)

Any ideas? This is my first issue report so apologies if I am doing it incorrectly. Found this project through some of your talks, great work :)!

**Comment by rvrsh3ll** [comment]
OS Windows 10?

**Comment by rvrsh3ll** [comment]
Provide a step-by-step how to generate this issues. It's working as intended on my side. Thank you!

**Comment by choppersec** [comment]
Windows 10 Enterprise (Evaluation - Build 201609) VMware, available here:
https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

Can you recommend another VM source or build that it works on? Thanks

**Comment by choppersec** [comment]
Got the same error on Windows 7 service pack 1. VM downloaded from the same location as above. 
Attempted to use the VBS launcher and got the following error on the same box (Win7):

![untitled](https://cloud.githubusercontent.com/assets/22639984/19159217/91dad138-8be3-11e6-8fff-018c2dc25b94.png)

**Comment by rvrsh3ll** [comment]
Can you screenshot how exactly you're making your launcher?

**Comment by choppersec** [comment]
```
>usestager windows/launcher_bat
>set Listener HQbox
>generate
```
Then I just copy the launcher.bat over to the VM and run it.

**Comment by choppersec** [comment]
I just ran the reset.sh script and created a new http listener, everything seems to be working fine now. I was using a meterpreter listener previously. It may have also been that I was using a listener created a week ago before I pulled the new changes today.

**Comment by rvrsh3ll** [comment]
Thanks for the update!
