### ISSUE TITLE
2.0_beta scriptimport function fails to import scripts

### ISSUE THREAD

**Issue by Dcellular** [adaptivethreat/Empire#352]
Empire Version 2.0_beta
OS: Kail 2 rolling

Screenshot is of interaction with a live Agent and attempting to import PowerUpSQL.ps1 via the _scriptimport_ command:
<img width="638" alt="screen shot 2016-10-06 at 1 03 51 pm" src="https://cloud.githubusercontent.com/assets/7376888/19164426/88e95f04-8bc5-11e6-8f1f-319a5ca0fdfd.png">

Note: This is the most recent release of PowerUpSQL being imported as of this post and is PowerShell V2 compliant.  Importing other scripts have also resulted in this error.

**Comment by rvrsh3ll** [comment]
this should be fixed now. feel free to re-open if you have issues
