### ISSUE TITLE
privesc/ms16-032 fails with Exception: 'launcher' error

### ISSUE THREAD

**Issue by atkinsj** [adaptivethreat/Empire#359]
## Empire Version
2.0_beta fresh pull

## OS Information (Linux flavor, Python version)
Local: Kali rolling
Remote: Windows 8.1

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Run new Empire agent.
Attempt to use privesc/ms16-032

## Screenshot of error, embedded text output, or Pastebin link to the error

> (Empire: powershell/privesc/ms16-032) > set Listener http
(Empire: powershell/privesc/ms16-032) > run
[>] Module is not opsec safe, run? [y/N] y
[!] Exception: 'launcher'

**Comment by rvrsh3ll** [comment]
Thank you for the submission. This has been fixed!

**Comment by llovoll** [comment]
I encountered the same problem, how can you solve, thank you.   [!] Exception: 'launcher'
