### ISSUE TITLE
Documentation/error handling around smbscanner could use some work

### ISSUE THREAD

**Issue by atkinsj** [adaptivethreat/Empire#360]
## Empire Version
2.0_beta fresh pull

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
powershell/situational_awareness/network/smbscanner says that 'UserName' and 'Password' is not required; this implies that it might attempt a GUEST login or something. If you don't specify them it doesn't error out and then attempts to invoke it on the agent anyway:

> Empire: powershell/situational_awareness/network/smbscanner) > run
> [>] Module is not opsec safe, run? [y/N] y
> [!] Username and password must be specified.
> (Empire: powershell/situational_awareness/network/smbscanner) > 
> Job started: KL28X5
> 
> Invoke-SMBScanner completed

**Comment by rvrsh3ll** [comment]
Thanks for the info. I've made Username/Password mandatory.
