### ISSUE TITLE
'shell' command output should indicate when a command completed and returned no stdout

### ISSUE THREAD

**Issue by atkinsj** [adaptivethreat/Empire#361]
## Empire Version

2.0_beta fresh pull
## OS Information (Linux flavor, Python version)

Local: Kali rolling up to date
Remote: Windows and Linux
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

> (Empire: E8NA27WT) > shell wmic qfe get Caption,Description,HotFixID,InstalledOn
> (Empire: E8NA27WT) > 

Matching debug output:

> 2016-10-09 21:05:22 Agents : [_] Tasked E8NA27WT to run TASK_SHELL
> 2016-10-09 21:05:25 listeners/http : [_] GET request for 192.168.0.118/login/process.php from 192.168.0.116
> 2016-10-09 21:05:25 Agents : [_] handle_agent_data(): sessionID E8NA27WT issued a TASKING_REQUEST
> 2016-10-09 21:05:25 listeners/http : [_] Agent from 192.168.0.116 retrieved taskings
> 2016-10-09 21:05:25 Agents : [_] handle_agent_data(): sessionID E8NA27WT issued a RESULT_POST
> 2016-10-09 21:05:25 Agents : [_] Agent E8NA27WT returned results.
> 2016-10-09 21:05:25 listeners/http : [*] Valid results return by 192.168.0.116

The same can be seen on Linux if for example you do a 'shell who' to see who is logged in, and nobody is, the command completes and there is no indication in the console that it even ran. It would be great to indicate this.

**Comment by atkinsj** [comment]
It might be helpful to update the documentation to include the fact that a 'shell' command on Windows is PowerShell and not cmd.exe. It should be obvious but I've had a few questions and for example the above wmic command is not valid in PowerShell, it returns a 'Invalid GET Expression.' error (which Empire does not display as output for some reason) but runs fine as shell cmd.exe /c "wmic qfe get Caption,Description,HotFixID,InstalledOn".

Sorry for all the issues and I know some are unfun doco/check updated but it'd be great to get Empire polished! :)

**Comment by xorrior** [comment]
This should require only a small amount of code in the agent. I'll try to get this implemented in the next week.

**Comment by xorrior** [comment]
Added. Note: applies for all shell commands except hostname and (mv|move|copy|cp|rm|del|rmdir).
