### ISSUE TITLE
Error in writing on a module

### ISSUE THREAD

**Issue by Ajimi** [adaptivethreat/Empire#367]
## Empire Version

ALL

## OS Information (Linux flavor, Python version)

ALL

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

in the directory Empire/lib/modules/trollsploit/message.py

the info object exactly description

'Description': ("Displays a specified message to the a user."),

Notice to the **a** user ..   change it to the user

**Comment by rvrsh3ll** [comment]
Fixed. Thank you.
