### ISSUE TITLE
Problem at running Empire

### ISSUE THREAD

**Issue by arekik6** [adaptivethreat/Empire#373]
## Empire Version

1.6.0
## OS Information (Linux flavor, Python version)

Kali Linux 64bit
## Screenshot of error, embedded text output, or Pastebin link to the error

root@kali:~/Téléchargements/Empire-master# ./empire
Traceback (most recent call last):
  File "./empire", line 10, in <module>
    from lib.common import empire
  File "/root/Téléchargements/Empire-master/lib/common/empire.py", line 31, in <module>
    import agents
  File "/root/Téléchargements/Empire-master/lib/common/agents.py", line 22, in <module>
    import http
  File "/root/Téléchargements/Empire-master/lib/common/http.py", line 67, in <module>
    class RequestHandler(BaseHTTPRequestHandler):
  File "/root/Téléchargements/Empire-master/lib/common/http.py", line 73, in RequestHandler
    serverVersion = helpers.get_config('server_version')[0]
TypeError: 'NoneType' object has no attribute '**getitem**'

**Comment by leesoh** [comment]
If you run `reset.sh`, does that resolve your error? I've had this a few times, mainly after switching branches. I ended up just using one local repo per branch and that solved a lot of my headaches.

**Comment by rvrsh3ll** [comment]
What leesoh said 👍

**Comment by arekik6** [comment]
Same problem after running reset.sh
Actually there is an error appearing in installation says
`E: Impossible de trouver le paquet swig`
and it's a result of this command
`apt-get install -y python-dev python-m2crypto swig python-pip`

**Comment by rvrsh3ll** [comment]
This may be a language issue?

**Comment by HarmJ0y** [comment]
FYI in the future, if you're running on a different language pack, if you can provide the English translations of the error messages it will help facilitate our troubleshooting :)

Google translate tells us that "Impossible de trouver le paquet swig" means that the swig package couldn't be found, which would be an OS repository issue. Can you try pulling the 2.0_beta branch by chance and seeing if the core code runs despite that package not being installed?

**Comment by arekik6** [comment]
Thanks everyone I've already fixed the issue by modifying the `sources.list` file
