### ISSUE TITLE
Issue Obtaining RESTful API Token

### ISSUE THREAD

**Issue by i128** [adaptivethreat/Empire#374]
## Empire Version
Master Branch under: https://github.com/adaptivethreat/Empire

## OS Information (Linux flavor, Python version)
x64 of Ubuntu 14.04.2

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When sending an authenticated POST request to /api/admin/login, the server responds back with a 401 unauthorized. The expected response would be the API token. Example posted in screens shots.  

## Screenshot of error, embedded text output, or Pastebin link to the error
Screen shot of server hosted on EC2
![image](https://cloud.githubusercontent.com/assets/2417131/19462346/cdebf748-94b1-11e6-9337-1d2d9b432fe9.png)

Screenshot of test CURL cmd from client
![image](https://cloud.githubusercontent.com/assets/2417131/19462352/d24610d0-94b1-11e6-9fb9-76af6dc42925.png)

## Any additional information
This used to work up-to a few weeks ago, maybe a few days.

**Comment by xorrior** [comment]
The rest API is still a WIP and still in Beta. We will move our focus to this once we release version 2.
Thanks
