### ISSUE TITLE
Missing packages during install on Kali Light

### ISSUE THREAD

**Issue by andywaugh** [adaptivethreat/Empire#375]
## Empire Version
1.5/1.6

## OS Information (Linux flavor, Python version)
Kali 64 bit light (2016.2)
Python 2.7.12+

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

install.sh completes successfully but Empire reports it is missing OpenSSL when run. 

Fresh install of Kali Light.Kali Light doesn't include libssl-dev or PyOpenSSL; I assume the full version does...

## Screenshot of error, embedded text output, or Pastebin link to the error

http://pastebin.com/fydKcJgJ

## Any additional information

To fix:
apt-get install libssl-dev
pip install pyopenssl

2.0_beta branch seems to already have libssl-dev but probably also needs pyopenssl?

**Comment by rvrsh3ll** [comment]
Fixed. Thanks for the heads-up!!
