### ISSUE TITLE
Hide pop-up window with .sct launcher

### ISSUE THREAD

**Issue by qgrosperrin** [adaptivethreat/Empire#376]
## Empire Version
1.6.0 

## Info
When using the launcher_sct, an empty Powershell pop-up window briefly appears on the target machine running the regsvr32 loader. This is likely to cause suspicion of compromise on the victim's end and can be avoided.

## Changes required
The following line needs to be updated https://github.com/adaptivethreat/Empire/blob/293f06437520f4747e82e4486938b1a9074d3d51/lib/stagers/launcher_sct.py#L102

to:
```python
            code += "           var r = new ActiveXObject(\"WScript.Shell\").Run(\"" + launcher + "\",0);\n"
```
Note the added `,0` part, towards the end of the line

See this for more details
https://github.com/rapid7/metasploit-framework/pull/6961#issuecomment-225277650

**Comment by rvrsh3ll** [comment]
Nice fix! Thanks will apply to both Empire versions.
