### ISSUE TITLE
empire migrate to metasploit, pass shell http, session invalid

### ISSUE THREAD

**Issue by ericmcwhite** [adaptivethreat/Empire#377]
## Empire Version
everytime  I empire migrate to metasplot, it created a session but 10 second it died because it is invalid.

**Comment by HarmJ0y** [comment]
This could be a large number of things (AV/HIPS stuff, firewall/network filtering, updates in MSF's HTTP transport negotiation, error in our code, etc).

Please explain in a bit more detail what exactly you're doing:

- the version of Empire and the port/listener type you're using
- the version of MSF and the port/listener type you're using
- whether the Empire and MSF servers are on the same machine
- what module you're running on the Empire side and what configuration parameters you're using

FYI for the future, please follow the issue template (version info/etc.) or we will automatically close the issue without further comment. If we don't have the proper information from your end we can't hunt down the issue. "It broke/doesn't work" doesn't really give us much to go on for troubleshooting.

**Comment by ericmcwhite** [comment]
I install newest empire and metasploit and it has worked. session has been created. but has to be on LAN.
Wan is not successful. Thanks a lot!!
