### ISSUE TITLE
[2.0_beta] Agent fails to connect to listener (Windows 2008 R2 server)

### ISSUE THREAD

**Issue by rokups** [adaptivethreat/Empire#379]
## Empire Version

`HEAD` of `2.0_beta` branch.
## OS Information (Linux flavor, Python version)

Archlinux, Python 2.7.12, Target is Windows 2008 R2 server VM.

```
(Empire: listeners) >  listeners/http : [*] GET request for 192.168.1.100:8080/admin/get.php from 192.168.122.248
 Agents : [*] handle_agent_data(): sessionID 00000000 issued a STAGE0 request
 listeners/http : [*] Sending POWERSHELL stager (stage 1) to 192.168.122.248
 Agents : [!] handle_agent_data(): routingPacket wrong length: 18
 Agents : [!] handle_agent_data(): routingPacket wrong length: 18
```

Loading from VM `192.168.1.100:8080/admin/get.php` gives nginx 'It Works!' page, loading `192.168.1.100:8080` gives error 404. Firewall is off as well.

**Comment by HarmJ0y** [comment]
So this could be a number of things, unfortunately, though we have a few ideas of what the core issue might be. Go ahead and repull (we just pushed https://github.com/adaptivethreat/Empire/commit/696e4ff752e8f75130a53992a4adb54887a2552e) and paste the debug output again.

The first POSTs from the key-negotiation stager should be ~400 bytes or so and the second should be around 200, so it looks like something wonky may be going on in the key negotiation code. The increased debug output should let us narrow it down more.

**Comment by rokups** [comment]
This is what i got:

	(Empire) >  listeners/http : [*] GET request for 192.168.1.100:8080/news.php from 192.168.122.248
	listeners/http : [*] GET cookie value from 192.168.122.248 : session=At4MIFzZb6iUDtVbal0g3liVzk0=
	Agents : [*] handle_agent_data(): sessionID 00000000 issued a STAGE0 request
	listeners/http : [*] Sending POWERSHELL stager (stage 1) to 192.168.122.248
	listeners/http : [*] POST request data length from 192.168.122.248 : 18
	Agents : [!] handle_agent_data(): routingPacket wrong length: 18
	listeners/http : [*] POST request data length from 192.168.122.248 : 18
	Agents : [!] handle_agent_data(): routingPacket wrong length: 18

Maybe ill try tomorrow make it dump sent data and see if it gives any clues.

**Comment by rokups** [comment]
It appears to be some binary data that tells nothing obvious to me.
I also tested windows 8.1 and very same code revisio properly connects. Likely issue with powershell version?

**Comment by atkinsj** [comment]
So I had two separate issues with a Server 2008 R2 host recently: a listener that used SSL did *not* work, it staged and then would not communicate further. I also had to install .NET 3.5 despite 2.0 and 4.0 being available.

Does trying either of those things fix it for you?

**Comment by rokups** [comment]
Installing .NET 3.5 indeed does make it work.

**Comment by rokups** [comment]
Quick look at stager code revealed this:

    $AES=New-Object System.Security.Cryptography.AesCryptoServiceProvider;

AesCryptoServiceProvider is introduced in .NET 3.5. According to [post on stackoverflow](http://stackoverflow.com/questions/5007262/aescryptoserviceprovider-alternate-in-net-2-0) we are supposed to use [RijndaelManaged](http://msdn.microsoft.com/en-us/library/system.security.cryptography.rijndaelmanaged.aspx).

**Comment by atkinsj** [comment]
Yup. I don't have the issue handy but Empire requires NET 3.5+ and there's
no intention or changing that. I've been using DISM to install it.

**Comment by rokups** [comment]
From 2.0 branch i got an impression that intention was to get empire running on as many machines as possible. Being able to run on powershell 2.0 immediately brought in w2k8 servers, but .NET 3.5 dependency basically throws out good portion of those machines. Too bad, considering empire can not run on legacy systems already.
