### ISSUE TITLE
2.0 Beta osx/webcam module fail

### ISSUE THREAD

**Issue by RPIKal** [adaptivethreat/Empire#382]
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

When interacting with an agent launch on my MacBookPRO (10.8.5) everything looks to be working fine exept for the webcam module which only saves a 24kb file with the right name but it seems corrupted :/ And i don't see the LED on the camera actually going green !

I tried to launch the last version of imageSnap on the computer with the command 👍 
./imagesnap -d Built-in\ iSight

And it works like a charm, could you help me find where the error is coming from ? :)

Thanks u very much
## Any additional information

EDIT : By changing line 86
run_command('%sdebug -w 2 %sdebug.jpg')
to
run_command('%sdebug -w 2 -d Built-in\ iSight %sdebug.jpg')

I got the LED to blink but the file is still corrupted :/

**Comment by rvrsh3ll** [comment]
Thanks for the info. We'll check it out.

**Comment by xorrior** [comment]
Looks like this is an issue with how the agent is returning data. This issue also exists in the native_screenshot module. Possibly an issue with any module that returns output. Maybe it's in the build_response_packet function for 101 type packets @HarmJ0y ? Not entirely sure, but I'll keep troubleshooting.

**Comment by xorrior** [comment]
Fixed. https://github.com/adaptivethreat/Empire/commit/e5bf4681587db320559375c891a84194ab3f4df3
