### ISSUE TITLE
Exception when using 'management/spawnas'

### ISSUE THREAD

**Issue by jbarg** [adaptivethreat/Empire#386]
hey there,
when i execute the spawnas module, an exception occures: 

[!] Error in runas: Exception calling "Start" with "1" argument(s): "The directory name is invalid"

Any ideas?

**Comment by rvrsh3ll** [comment]
Hi jbarg, can you proivde a few more details. What OS is your agent on? Screenshot? try running empire with ./empire --debug for more output
