### ISSUE TITLE
Random/strange reconnects 

### ISSUE THREAD

**Issue by bkr32** [adaptivethreat/Empire#388]
## Empire Version
1.6

## OS Information (Linux flavor, Python version)
Kali rolling 2016.2

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
So I created a listener and a stager and ran it on a remote PC, so far so good, left it for a couple of hours today and i saw strange unknown devices have spawned a session, with external IP addresses being from France us and UK , all have different names and subnets, these sessions also spawned in metasploit, is this a known issue?

## Screenshot of error, embedded text output, or Pastebin link to the error

https://drive.google.com/file/d/0B_95SCaieYQUcmZId2hDSG0zWWM/view?usp=drivesdk

## Any additional information
I'm pretty sure I didn't open or launch any type of stager on these machines

**Comment by rvrsh3ll** [comment]
This may be hard to fix. How did you distribute your payload?

**Comment by bkr32** [comment]
The payload was distributed via macro, added in a word file transported via flash disk

**Comment by rvrsh3ll** [comment]
JOHN-PC is a known sandbox pc name. Looks like someone is analyzing your payload

**Comment by bkr32** [comment]
Interesting so those are sandbox pc's
