### ISSUE TITLE
Mimikatz issues Windows 10 1607 BUILD 14393.351

### ISSUE THREAD

**Issue by yannickwe87** [adaptivethreat/Empire#389]
## Empire Version
Latest

## OS Information (Linux flavor, Python version)
N.A.

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Mimikatz does not produce login output, instead it gives:

<code>
mimikatz(powershell) # sekurlsa::logonpasswords
ERROR kuhl_m_sekurlsa_acquireLSA ; Logon list

mimikatz(powershell) # exit
Bye!
</code>

## Any additional information
User is administrator, the latest build from source (gentlekiwi) works like a charm, so it appears changes made by gentlekiwi have not yet found its way to the empire build

**Comment by rvrsh3ll** [comment]
We should be updating Invoke-Mimikatz soon and updating Empire with it as well.

**Comment by rvrsh3ll** [comment]
Empire 2.0_beta branch has been updated with the latest mimikatz. Please let us know if you have any further issues.
