### ISSUE TITLE
[feature request]  integrate Invoke-Obfuscation   into powershell stagers 

### ISSUE THREAD

**Issue by thesle3p** [adaptivethreat/Empire#390]
In the interest of Opsec would it be possible to have empire invoke https://github.com/danielbohannon/Invoke-Obfuscation before running a stager to get past AMSI (also have the option to obfuscate  Invoke-Obfuscation would help)  before the empire payload is staged? that way AMSI and AV that uses it will have a harder time detecting Empire and the utilities  it runs?

**Comment by HarmJ0y** [comment]
So Invoke-Obfuscation is great, but it's a PowerShell script, so it won't work on our Python/Linux based Empire control server, so true integration is not going to be possible. We're also resistant to running all scripts through the obfuscator manually on a regular basis, as we don't want to get into a cat and mouse game with AV vendors. We would rather leave obfuscation at this point to the operator, but we will consider integrating a different obfuscation approach at some point in the future.

**Comment by thesle3p** [comment]
In that case would it be possible to give stagers the option to upload
and run ANY script before it sends the actual agent? This would be
useful not just for AV evasion but sandbox detection.
