### ISSUE TITLE
Agents on Server 2008 R2 without .NET 3.5 do not beacon

### ISSUE THREAD

**Issue by atkinsj** [adaptivethreat/Empire#391]
## Empire Version
2.0_beta, fresh git pull with a ./setup/reset.sh

## OS Information (Linux flavor, Python version)
Kali rolling
Windows Server Server 2008 R2, fully windows updated, no .NET 3.5.1 feature enabled

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
1. Start new http listener
2. Generate standard powershell launcher
3. Paste in to command prompt
4. No agent beacons back, debug included below
5. Enable .NET 3.5.1
6. Paste in to command prompt
6. Agent beacons back

This is 100% reproducible for me. Judging by #67 and #315 it looks like we thought this was resolved but I'm still seeing it. No error is generated even if i base64 decode and execute the PowerShell directly in to an interactive PowerShell prompt.

## Screenshot of error, embedded text output, or Pastebin link to the error

> 2016-10-09 22:35:53 listeners/http : [*] GET request for 192.168.0.118/news.php from 192.168.0.116
> 2016-10-09 22:35:53 listeners/http : [*] GET cookie value from 192.168.0.116 : session=HICxe9UhteN5RGDlxnrHRqGM4Y4=
> 2016-10-09 22:35:53 Agents : [*] handle_agent_data(): sessionID 00000000 issued a STAGE0 request
> 2016-10-09 22:35:53 listeners/http : [*] Sending POWERSHELL stager (stage 1) to 192.168.0.116
> 2016-10-09 22:35:54 listeners/http : [*] POST request data length from 192.168.0.116 : 18
> 2016-10-09 22:35:54 Agents : [!] handle_agent_data(): routingPacket wrong length: 18
> 2016-10-09 22:35:54 listeners/http : [*] POST request data length from 192.168.0.116 : 18
> 2016-10-09 22:35:54 Agents : [!] handle_agent_data(): routingPacket wrong length: 18
>

**Comment by rvrsh3ll** [comment]
.NET is required for Empire to work.

**Comment by leechristensen** [comment]
.NET 3.5 is required for Empire to work on Server 2008 R2 due to the .NET framework on Server 2008 R2 missing core crypto libraries.  For more details, see https://github.com/adaptivethreat/Empire/issues/325#issuecomment-250988382

**Comment by atkinsj** [comment]
Thanks dudes. I thought we'd come to that conclusion but then couldn't find
the ticket and thought I was crazy! Sorry about that.
