### ISSUE TITLE
empire did not generate any agents, metasploit only send stage to ip and did not create a meterpreter

### ISSUE THREAD

**Issue by ericmcwhite** [adaptivethreat/Empire#397]
## Empire Version
1.6

## OS Information (Linux flavor, Python version)
kali linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
I send the target (  location is in Europe) both macro and batch agent and did not generate any agents. 
I test on wan ( in the same city not same LAN) and they were working. I also send the target meterpreter but every time only sending stage and stuck there( no sessions has been created). any idea? What kind of AV can do this? Thanks

**Comment by rvrsh3ll** [comment]
Hello, thanks for the issue notification. There's probably too many possibilities at play here to say for certain what's happening. It could be border protections such as a Palo Alto device or host protections of some sort. Really no way to tell with the information provided.
