### ISSUE TITLE
Empire fails to open Profiles 

### ISSUE THREAD

**Issue by thesle3p** [adaptivethreat/Empire#399]
So when I attempt to set a Default profile with set DefaultProfile /path/to/profile/file  I get a generic Error opening Profile file /path/to/profile/file. I tested this with all the profiles Empire ships with as well as safe_browsing.txt from Empyre

**Comment by rvrsh3ll** [comment]
You're supposed to copy the text out of the profile and paste it in there. The value does not take paths.
