### ISSUE TITLE
new mimikatz doesn't store creds

### ISSUE THREAD

**Issue by tiehfood** [adaptivethreat/Empire#400]
## Empire Version
2.0_beta

## OS Information (Linux flavor, Python version)
kali linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
new mimikatz version doesn't store credentials in the empire database.
older version of mimikatz works perfect.

**Comment by rvrsh3ll** [comment]
Thanks for the head's up. WIll work on it!

**Comment by rvrsh3ll** [comment]
Fixed and updated to version 2.1 20161126
