### ISSUE TITLE
Listener error after last update

### ISSUE THREAD

**Issue by HackM3nt3** [adaptivethreat/Empire#408]
I  used my external ip and the framework don't let me set the listener, always get these ports errors,
what should i do to fix this?
(Empire: listeners) > list
[!] No listeners currently active 
(Empire: listeners) > set Port 9998
(Empire: listeners) > execute
[!] Error starting listener on port 9998: [Errno 99] Cannot assign requested address
[!] Error starting listener on port 9998, port likely already in use.
(Empire: listeners) > set Port 666
(Empire: listeners) > execute
[!] Error starting listener on port 666: [Errno 99] Cannot assign requested address
[!] Error starting listener on port 666, port likely already in use.
(Empire: listeners) > set Port 1178 
(Empire: listeners) > execute
[!] Error starting listener on port 1178: [Errno 99] Cannot assign requested address
[!] Error starting listener on port 1178, port likely already in use.

**Comment by mubix** [comment]
See my comments in #407
