### ISSUE TITLE
Invoke-PSInject.ps1 error not returning agent found and corrected

### ISSUE THREAD

**Issue by PoSHMagiC0de** [adaptivethreat/Empire#410]
## Empire Version
1.6.0

## OS Information (Linux flavor, Python version)
Kali 4.6.0

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Found out why the psinject doesn't always work.  It was peculiar since if I staged an empire dll and used reflectiveinject module it worked fine.  Copied over powershell modules to my windows test machine and did some testing.
Found out that at line 44 of the invoke-psinject module the size for the PoshCode string is 1200. Unfortunately, all the Powershell empire modules that come out of launcher is encoded to a size of 1330 or 1339.  This of course will throw an error.  Stager has grown there guys.  I do not know the anatomy of your dlls but took a risk and expanded that size to 1400.  I injected your payload again directly running module on test machine and it works.
Modified invoke-psinject.ps1 in Powershell Empire data/modules_source folder and tested with success.

**Comment by xorrior** [comment]
This has been fixed in the 2.0_beta branch and now 1.6.
