### ISSUE TITLE
[2.0_beta] powershell/management/spawnas throws [!] Exception: 'launcher_bat'

### ISSUE THREAD

**Issue by atkinsj** [adaptivethreat/Empire#412]
## Empire Version
Empire 2.0_beta, fresh pull

## OS Information (Linux flavor, Python version)
Kali rolling, freshly updated

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Attempting to spawn a new Empire agent as another user using management/spawnas fails with an exception.

## Screenshot of error, embedded text output, or Pastebin link to the error
> (Empire: RU8GM9SA) > usemodule management/spawnas
> (Empire: powershell/management/spawnas) > options
> 
>               Name: Invoke-SpawnAs
>             Module: powershell/management/spawnas
>         NeedsAdmin: False
>          OpsecSafe: False
>           Language: powershell
> MinLanguageVersion: 2
>         Background: False
>    OutputExtension: None
> 
> Authors:
>   rvrsh3ll (@424f424f)
>   @harmj0y
> 
> Description:
>   Spawn an agent with the specified logon credentials.
> 
> Comments:
>   https://github.com/rvrsh3ll/Misc-Powershell-
>   Scripts/blob/master/RunAs.ps1
> 
> Options:
> 
>   Name       Required    Value                     Description
>   ----       --------    -------                   -----------
>   UserName   False                                 Username to run the command as.         
>   CredID     False                                 CredID from the store to use.           
>   Domain     False                                 Optional domain.                        
>   Proxy      False       default                   Proxy to use for request (default, none,
>                                                    or other).                              
>   Listener   True                                  Listener to use.                        
>   ProxyCreds False       default                   Proxy credentials                       
>                                                    ([domain\]username:password) to use for 
>                                                    request (default, none, or other).      
>   UserAgent  False       default                   User-agent string to use for the staging
>                                                    request (default, none, or other).      
>   Password   False                                 Password for the specified username.    
>   Agent      True        RU8GM9SA                  Agent to run module on.                 
> 
> (Empire: powershell/management/spawnas) > set UserName domainadmin
> (Empire: powershell/management/spawnas) > set Domain TESTNET
> (Empire: powershell/management/spawnas) > set Password P@SSw0rd
> (Empire: powershell/management/spawnas) > set Listener https
> (Empire: powershell/management/spawnas) > run
> [>] Module is not opsec safe, run? [y/N] y
> [!] Exception: 'launcher_bat'

**Comment by xorrior** [comment]
This was due to the incorrect key being used to generate the launcher. Fixed in the 2.0_beta branch.
