### ISSUE TITLE
[2.0_beta] Empire uses 100% CPU if it receives a tasking packet that contains more than one task

### ISSUE THREAD

**Issue by atkinsj** [adaptivethreat/Empire#413]
## Empire Version
Empire 2.0_beta, freshly pulled

## OS Information (Linux flavor, Python version)
Empire agent: Server 2012 R2 fully updated
Empire C2: Kali rolling freshly updated

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
1. Stage a new PowerShell agent
2. Wait a few seconds for it to stage
3. Run 'sysinfo'
4. Sysinfo will return successfully
5. up-arrow sysinfo twice in rapid succession (i.e., queue up 2 tasks for the next Empire call-back)
6. Empire now uses 100% CPU and is no longer responding to any tasking

## Screenshot of error, embedded text output, or Pastebin link to the error
The bug is in [this while loop](https://github.com/adaptivethreat/Empire/blob/2.0_beta/data/agent/agent.ps1#L986). It never terminates; you can see this bug in particular by adding a Write-Output to the start of the while loop and then staging a new agent without -W Hidden and -NonI.

This has bricked several boxes for me in recent tests so if someone with a little more PowerShell and/or Empire knowledge than me could take a look that would be awesome!

**Comment by atkinsj** [comment]
The fix for this is to add:

`$Remaining = $Decoded[6]` at line 994.

**Comment by xorrior** [comment]
Thanks for the suggestion! Applied your fix with a small change and confirmed that the issue doesn't occur.
