### ISSUE TITLE
code_execution/invoke_reflectivepeinjection hangs empire if an invalid path is provided to DllPath

### ISSUE THREAD

**Issue by atkinsj** [adaptivethreat/Empire#421]
## Empire Version
2.0_beta fresh pull

## OS Information (Linux flavor, Python version)
Kali rolling fully updated

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
1. usemodule code_execution/invoke_reflectivepeinjection
2. Set DllPath to an invalid path
3. Run

## Screenshot of error, embedded text output, or Pastebin link to the error
This cause the Empire agent to stop beaconing; an error message is returned but a script is still tasked and sent to the agent. The script that is sent is 'Invoke-ReflectivePeInjection' with no arguments. If you run Empire without window hidden and noni, the Invoke-ReflectivePeInjection script is actually hanging on a prompt for PEUrl (the default if you provide no arguments to the module).

The catch block in the code_execution/invoke_reflectivepeinjection should cause the module to fail and not task the agent with an empty powershell invoke.

**Comment by xorrior** [comment]
Fixed. Add an if statement to catch if both options are not set. Now either one will be required.

**Comment by atkinsj** [comment]
@xorrior I was going to open a new issue but thought I'd ping you here for context, the if statement you added is an 'or' and should be an 'and'. This means that it errors unless you specify both a PEUrl and a DllPath which naturally doesn't work.

**Comment by xorrior** [comment]
Fixed. Sorry about that.
