### ISSUE TITLE
PoshCode in Invoke-PSInject too long

### ISSUE THREAD

**Issue by turkja** [adaptivethreat/Empire#423]
## Empire Version
1.6

## Target
Windows7 64-bit

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When _data/module_source/management/Invoke-PSInject.ps1_ is generated, sometimes the PoshCode argument exceeds 1200 characters and injection fails (line 44):

   [ValidateLength(1,1200)]

If this is changed to something like 2000 characters, injection is successful.

**Comment by xorrior** [comment]
This has been fixed in the 2.0_beta branch and now 1.6.
