### ISSUE TITLE
screenshot module

### ISSUE THREAD

**Issue by milcaca** [adaptivethreat/Empire#435]
## Empire Version
Empire2.0

## OS Information (Linux flavor, Python version)
Linux debian 8 

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Following taking control (userland) of a windows 7 server I try to take a screenshot which seems to be successfull but no way to retrieve the file.

**Comment by xorrior** [comment]
Can you please elaborate when you say, "no way to retrieve the file"? The raw bytes from the image are base64 encoded and returned to the server. You should receive output after the screenshot is taken. The file should be saved in the downloads folder.

**Comment by milcaca** [comment]
When using the screenshot functionality with the 2.0 version I cannot retrieve the picture nothing is store in ./downloads/ID
. No issue with master Branch.

**Comment by xorrior** [comment]
Fixed in latest commit.
