### ISSUE TITLE
uninstall program

### ISSUE THREAD

**Issue by legendary77** [adaptivethreat/Empire#436]
## Empire Version

 wmic no work in shell
`
shell wmic product get name
	
shell wmic product where name="Microsoft Security Client" call uninstall /nointeractive

shell cmd /k wmic product where name="Microsoft Security Client" call uninstall /nointeractive
`

**Comment by enigma0x3** [comment]
What do you mean "wmic no work in shell". Are you able to execute other shell commands? What OS and version of Empire? Please give more information than that.

Thanks.

**Comment by xorrior** [comment]
@legendary77 When submitting issues please follow the template and provide more detail so that we can adequately diagnose the issue.
