### ISSUE TITLE
Trigger stager

### ISSUE THREAD

**Issue by Kratos120** [adaptivethreat/Empire#444]
i have a victim machine and use persistence/elevated/wmi on startup with success,if i have open empire and victim start  pc i have agent but what happent if open empire 1 hour or more after victim machine i dont have agent,stager steal calling or not ?and how can trigger to startup? or can tell me any methods to trigger stager to give me agent any time to open empire?

**Comment by killswitch-GUI** [comment]
https://github.com/adaptivethreat/Empire/blob/master/data/agent/agent.ps1#L36 

every agent has a limit to how many times it will check for C2 before it exits. I would set that accordingly.

**Comment by Kratos120** [comment]
thank you!

**Comment by killswitch-GUI** [comment]
np man !
